export const mobileProjects = [
  {
    title: 'E-Commerce Platform',
    description: 'A full-stack e-commerce solution with real-time inventory management, payment integration, and admin dashboard.',
    technologies: ['React', 'Node.js', 'PostgreSQL', 'Stripe'],
    image: 'https://images.pexels.com/photos/230544/pexels-photo-230544.jpeg?auto=compress&cs=tinysrgb&w=800',
    github: '#',
    demo: '#',
  },
  {
    title: 'Task Management App',
    description: 'A collaborative task management application with real-time updates, team workspaces, and project tracking.',
    technologies: ['React', 'TypeScript', 'Firebase', 'Tailwind CSS'],
    image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
    github: '#',
    demo: '#',
  },
  {
    title: 'Social Media Dashboard',
    description: 'Analytics dashboard for social media management with data visualization and automated reporting features.',
    technologies: ['React', 'Express', 'MongoDB', 'Chart.js'],
    image: 'https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=800',
    github: '#',
    demo: '#',
  },
  {
    title: 'Weather Forecast App',
    description: 'Real-time weather application with location-based forecasts, interactive maps, and weather alerts.',
    technologies: ['React', 'OpenWeather API', 'Mapbox', 'Tailwind CSS'],
    image: 'https://images.pexels.com/photos/1118873/pexels-photo-1118873.jpeg?auto=compress&cs=tinysrgb&w=800',
    github: '#',
    demo: '#',
  },
  {
    title: 'Blog Platform',
    description: 'A modern blogging platform with markdown support, user authentication, and content management system.',
    technologies: ['Next.js', 'Node.js', 'PostgreSQL', 'AWS S3'],
    image: 'https://images.pexels.com/photos/262508/pexels-photo-262508.jpeg?auto=compress&cs=tinysrgb&w=800',
    github: '#',
    demo: '#',
  },
  {
    title: 'Fitness Tracker',
    description: 'Mobile-responsive fitness tracking app with workout plans, progress tracking, and nutrition logging.',
    technologies: ['React', 'Node.js', 'MongoDB', 'Chart.js'],
    image: 'https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg?auto=compress&cs=tinysrgb&w=800',
    github: '#',
    demo: '#',
  },
];
